---
kind: pipeline
name: drone

workspace:
  base: /app
  path: git/drone

steps:
  - name: build
    image: golang:1.12
    commands:
      - go build
    environment:
      host:
        from_secret: 127.0.0.1
      port:
        from_secret: 22
      abc: abctest
  - name: deploy
    image: appleboy/drone-scp
    commands:
      - echo '123';
    when:
      status:
        - success
    settings:
      host:
        from_secret: 127.0.0.1
      port:
        from_secret: 22
      key:
        from_secret: rsa
      username:
        from_secret: wuhou
      target:
        from_secret: /data/go
      source: ./*

trigger:
  branch:
    - master
  event:
    - push
