---
kind: pipeline
name: drone

workspace:
  base: /data/build/go
  path: github.com/mytest

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    #image: golang:1.12
    image: yongsean/go1.12-revive
    commands:
      #- go get -u github.com/mgechev/revive
      #- go get -v -u golang.org/x/lint/golint
      - revive -formatter friendly ./
      - go build -o mytest
      - pwd

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
      branch:
        - master
        #- dev
    volumes:
      - name: go_id_rsa
        path: /data/go/id_rsa1
    settings:
      host: 172.18.140.140
      username: wuhou
      key_path: /data/go/id_rsa1
      target:
        - /data/go
      source:
        - mytest

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: go_id_rsa
    host:
      path: /data/go/id_rsa

trigger:
  branch:
    - master
  event:
    - push
