---
kind: pipeline
name: drone


workspace:
  base: /data/build/go
  path: github.com/mytest

steps:
  - name: build
    image: golang:1.12
    #volumes:
    #- name: cache
    #  path: /tmp/cache
    commands:
      - go build -o mytest
      - pwd

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
    commands:
      - ls /data
    settings:
      host: 172.18.140.140
      username: wuhou
      key_path: /data/go/id_rsa
      target:
        - /data/go
      source:
        - mytest

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - master
  event:
    - push
