---
kind: pipeline
name: drone

workspace:
  base: /data/build/go
  #path: github.com/mytest
  #path: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
  path: ${DRONE_REPO}

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: yongsean/go1.12-revive
    commands:
      - gorevive.sh ./
      - go build -o mytest
      - pwd

  - name: notify
    image: yongsean/drone-dingding
    when:
      status: [success, failure]
    settings:
      #token: a382c5d4e4dadee305d400f5edaeeb2807f179f4e40009f2c114d8ab19b368d3
      token: ${DING_TOKEN}

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
      branch:
        - master
        #- dev
    volumes:
      - name: go_id_rsa
        path: /data/go/id_rsa1
    settings:
      host: 172.18.140.140
      username: wuhou
      key_path: /data/go/id_rsa1
      target:
        - /data/go/${DRONE_REPO_NAME}
      source:
        - mytest




volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: go_id_rsa
    host:
      path: /data/go/id_rsa

trigger:
  branch:
    - master
  event:
    - push
