---
kind: pipeline
name: drone


workspace:
  base: /app
  path: git/drone

steps:
  - name: build
    image: golang:1.12
    volumes:
    - name: cache
      path: /tmp/cache
    commands:
      - go build
    environment:
      host:
        from_secret: 127.0.0.1
      port:
        from_secret: 22
      abc: abctest

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
    settings:
      host: 172.18.140.140
      port: 22
      key: 
	from_secret: rsa
      username: wuhou
      target: /data/go
      source: ./*

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - master
  event:
    - push
