---
kind: pipeline
name: drone

workspace:
  base: /data/build/go
  #path: github.com/mytest
  #path: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
  path: ${DRONE_REPO}

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    #image: golang:1.12
    image: yongsean/go1.12-revive
    commands:
      #- go get -u github.com/mgechev/revive
      #- go get -v -u golang.org/x/lint/golint
      - gorevive.sh ./
      - go build -o mytest
      - pwd

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
      branch:
        - master
        #- dev
    volumes:
      - name: go_id_rsa
        path: /data/go/id_rsa1
    settings:
      host: 172.18.140.140
      username: wuhou
      key_path: /data/go/id_rsa1
      target:
        - /data/go
      source:
        - mytest

  - name: notify
    image: yongsean/drone-dingding
#   image: lddsb/drone-dingtalk-message
    settings:
      webhook: https://oapi.dingtalk.com/robot/send?access_token=a382c5d4e4dadee305d400f5edaeeb2807f179f4e40009f2c114d8ab19b368d3
      #token: a382c5d4e4dadee305d400f5edaeeb2807f179f4e40009f2c114d8ab19b368d3
      #type: markdown
      #sha_link: true
      #message_color: true
      #message_pic: true


volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: go_id_rsa
    host:
      path: /data/go/id_rsa

trigger:
  branch:
    - master
  event:
    - push
