kind: pipeline
name: default

steps:
- name: apply ansible playbook
  image: plugins/ansible:1
  become: true
  become_method: su
  become_user: wuhou
  list_hosts: true
  list_tasks: true
  environment:
    another_var: foo
  settings:
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    private_key:
      from_secret: ansible_private_key
  when:
    event:
    - push
    - tag

---
kind: secret

data:
  ansible_private_key: -----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAw1LTILib3C4KMhEX0uL53C/5O3GnW5ZiJ/n9cqb2Pei7Hxwy
X4ELpspAJWiBkd7lRVwkezXerFEndfcIrf4nUUGsR2feqTqNxoqqKz0m838N5ggE
C8pbaA3REXEn4q38PT6f28SUq3Hr34PRF5SQ+WWigpXr63BfmNNMoV8OIp0hXoqZ
Ev6t/w6woAlpj9HrAbFKbhVZI0orLkfnQ4y08DAMtqSZ4ZqzGOqP8vBqwBB/Vh+X
/q3zpQ09DKLrUs5oZ0rpO8kKHTSILGmWoFFH9iW4fRBP4Ec+kTzr4couiCFQnGeN
hM0B/d/Kbmq7ClH0FXLtmtGQfuczWo9pw0Ey6QIDAQABAoIBAQC7VhALPSS3/Cxp
Mr2/1VTCG/0WR361uDmyj/HHal2YqUP3paqmsPWE5ky51E8ZokgRyztuNQ+6BCgt
216myrHZHHzpC7WiZ/ec6lgmGoPmXQDulNeUm2QqG75e1UHlBux7rTnTperVuPD7
MslzrVmS6ikAyFw7N09pG5hO2gWLqayS3JDeciWI730PlYL5IBAg6BXlhMeCXZps
KNEV2L+35WSXSDgkbLG9Wva57wfe3C6EyoN5sjWVu+vbM0GWUlXEGD9fQEDJC4SC
Zok/RhEy6NruGHpVEZUUd0gb7YqH9Dz/p0+n4Gy7+FvSD5Dsel3Xn1LxZKeUY7+J
zgtVrA2BAoGBAPVUnWrWX8yIlc/YOL5YbJJR+Lqnff/scQIAvBYvKZRjSVVt8kxe
xE9frCX+jkHzE6EkIolvdm6bodzycxPUeH03q16yCUCrW+cJ4uR9alKIegKrG93r
jaxNJIzAry77ldZ93/gI5MVhcGISSv1qaXTgAN2Xo3DBctjOJjPvb2/ZAoGBAMvR
dRnkt/wyJdnr92ognOOuToyRazuE82C/TvTyDgI8AQclyB1YIq72kGsIyOYmncOR
XRx8wrEsW31ERBR/JXs1XZ883qEsGnqwRgOao6zYHIq/QE5nHslRJZfrMBwD8jlm
W/WnHEWJcp0e1fvIVknW9RenbmNHL1qL1ZfmawGRAoGBAJQCh7J0QXnRkajCx4E3
MdGZONnLwT3M9WUC8nbj308SE6VB3uPqbL+Cdga6LDNnppkahuep4qbaqG33rCvz
jPnmwzIvcVudxqV+FnBJpgLDKfFAMGDUAzZHmFx+x3IuAPlWGfC31OWsYrQYWzvG
nncPyhXmrYmSfGqG/Q9qTi4JAoGBAKlCm+XR/DzTBH4SKNiYltG5mn+/7/ZwtZDd
rttZ/Oo8HHpsFODRpZP5LPvGQthmr1OO721N6n0qIhxISeVfpafJLKOl8BiWwLKs
mqg5jr1mh2Vt6CB0IKv82KRt6vkJCepDKBE8Iw1YVLdIuVmsCISvn8ByCgkmP5wJ
TmskLi8RAoGAOaa9YSKWbtV+V5nfRBwh7t8Lg9RvRJtxl5+/ocSPNsVRiKv+49XR
CN76YVxWuXXowkM31XOpla13D5wZCZFlwtxDnDuocHQ4QUqiVgyFCsnxFvY0hQqn
UetD2QZvwQ7EmhPhEZzA5YRmwuU01Cz1fiJO6zwVSEL0lhWb2LmDNtI=
-----END RSA PRIVATE KEY-----
